### ISSUE TITLE
Setting up Cloud Server Environment

### ISSUE THREAD

**Issue by oliversauter** [WorldBrain/Webmarks#17]
Acceptance Criteria:
 - [ ] Our servers are set up to run _Webmarks_ and to store data in a database
 - [ ] Our documentation adjusted and a step-by-step process of installation added.
 - [ ] Access to servers documented.

## Requirements:

We need a scalable server environment to set up WorldBrain's version of the hypothes.is installation and to store data.

**1. Managed Server or Cloud**
There is no staff to maintain the servers and its securities yet. A managed or cloud server is the right thing now. 

**2. Large Storage of Data**
We are going to save rather more than less data our users will produce. For example: We are going to save whole websites and their content. Users will also save a lot of pictures and files with their notes.

**3. Speed medium important but should be easily upgradeable**
In the beginning we will be the only ones tinkering on it and the closed alpha will also have a limited amount of users. But as soon as we on board more users, we should be able to easily upgrade the speed capacities. 

## Roadmap:

In case we should break these down in smaller tasks or they need more extensive explanation, feel free to leave a comment.

- [x] Making a list of cloud server solutions that are suitable ( @jlangstaff )
- [x] Deciding together which make sense
- [x] Ordering
- [x] Documenting Access Information
- [ ] Setting up WorldBrain installation
- [ ] Documenting Step-By-Step Process of Installation
- [ ] Testing installation process, (Explain it like I am five=Oliver) :smile: 

Thanks for your contribution!

**Comment by jlangstaff** [comment]
I had originally tried to compile a spreadsheet with a breakdown of all costs and uptime information. However, I was finding it pretty difficult to place all the companies pricing models on a standard baseline.

- Microsoft Azure (https://azure.microsoft.com/)
- Rackspace Cloud Server (https://www.rackspace.com/)
- Amazon EC2	(https://aws.amazon.com/ec2/)
- Google Cloud Platform (https://cloud.google.com/)
- Elastichosts (https://www.elastichosts.ca/)
- Softlayer (http://www.softlayer.com/)
- Joyent (https://www.joyent.com/)
- CloudSigma (https://www.cloudsigma.com/)
- CenturyLink (https://ca.ctl.io/)

Some info on uptime:
- https://cloudharmony.com/status
- http://searchcloudcomputing.techtarget.com/news/2240237323/Cloud-outage-audit-2014-reveals-AWS-on-top-Azure-down

**Comment by oliversauter** [comment]
Thanks for gathering this Jesse!

**Comment by mr-mig** [comment]
I would also consider Heroku: https://www.heroku.com/ as an easier option

**Comment by mr-mig** [comment]
If you would go with IaaS instead of PaaS, I'd suggest using Chef/Ansible for infra orchestration and Terraform as a cloud configuration tool. Also, have a look at the notion of "immutable infrastructure".

It will solve some problems:

- It will make documenting infrastructure easier (as it will be directly documented in code)
- The setup will be easily reproducible via tools instead of manual labor (spinning up new machines will be a matter of running a command)
- More or less standardized approach. It means newcomers won't suffer much.

**Comment by mr-mig** [comment]
You can find some nice comparison (heroku vs aws) here: http://stackoverflow.com/questions/9802259/why-do-people-use-heroku-when-aws-is-present-whats-distinguishing-about-heroku

**Comment by oliversauter** [comment]
What about we go for the current easier option, PaaS, and switch in 3-4 months (before Alpha Release) to an IaaS? (or as soon as we have someone on board who could manage everything)

As far as I understood are Heroku and Amazon Beanstalk comparable services, while amazon does not have additional costs besides the usual AWS costs - you just pay the instance. Heroku is in this case much more expensive. In our case the "Standard" Dyno (min. 25€) would make sense, but comes without a DB, which costs at least another 50€/month in the Standard tier.

So it seems, that Beanstalk is the choice to go with an PaaS.
The question remaining about how difficult it could be in case we want to change the provider in the mid-run? Or if we even need to, when staying with Amazon and just get rid of the Beanstalk Service.
Quote by [Beanstalk FAQ](http://aws.amazon.com/elasticbeanstalk/faqs/):
> However, with AWS Elastic Beanstalk, developers retain full control over the AWS resources powering their application. If developers decide they want to manage some (or all) of the elements of their infrastructure, they can do so seamlessly by using Elastic Beanstalk’s management capabilities.

How is the general compatibility with Hypothesis and its Javascript components with Beanstalk, which [supports](http://aws.amazon.com/elasticbeanstalk/getting-started/) node.js?

**Comment by mr-mig** [comment]
> As far as I understood are Heroku and Amazon Beanstalk comparable services, while amazon does not have additional costs besides the usual AWS costs

And they have no hosted DB, which is a separate component in AWS infra and also costs money. 

You won't be able to spare more than 30-50% at the beginning on ifra, unfortunately. 
The biggest difference will come with time, when you will need to scale the thing.

> The question remaining about how difficult it could be in case we want to change the provider in the mid-run?

You either will need a special dedicated person to take care of infra, or you need someone in the team doing this. 
If everything is more or less automated, it won't be hard. Tho you can think **2 weeks** at least in optimistic case.

> developers retain full control over the AWS resources powering their application.

Beanstalk is the best choice if you would like to migrate to AWS in the future to have more granular and low-level control over infra and prices. 

One of the upsides - it has **autoscaling** capabilities out of the box.

The thing you are missing - Heroku, compared to Beanstalk, has more plugins/features. E.g. logging and **application metrics**, databases, message queues, **continuous delivery**, e.g. 

It's basically paying for convenience and having less headache.

With Beanstalk one need to configure logging/metrics using services like AWS CloudWatch and Papertrail, for example.

> How is the general compatibility with Hypothesis and its Javascript components with Beanstalk, which supports node.js?

There should be no issues apart from managing the infra. 

---

Resume: I would say Beanstalk is a viable choice so far. It will come with some overhead initially, but provides more flexibility.

And do not forget about the [amazon free tier](https://aws.amazon.com/free/) :)

**Comment by oliversauter** [comment]
Hehe, yes the free tier...staring at me seductively :D

Ok, I think we then have a winner - Beanstalk.
So how to proceed from here?
Shall I order the Beanstalk with a minimum set up? 

Would you then have time and be willing to set up hypothes.is on the environment, so people can start working on?

**Comment by mr-mig** [comment]
You need to create a root AWS account (your own for billing) and then create dedicated accounts for users (IAM accounts) with all the necessary rights.

Starting from there I can pick it up and start setting things up.

P.S. We may want to sit together on this in a cafe/coworking to pair on all the shit together.

**Comment by oliversauter** [comment]
Ok, will do this and will get back to you as soon as i got it.

Sounds like a good idea, I wont be in Berlin until the 1. of March though. Maybe we try to resolve the important issues in a skype session?

But first comes first, lets speak again, when I set it up :)

Thanks for your help on this!

**Comment by oliversauter** [comment]
Update: Is created and sent to Alexey. He is now in the process of setting everything up.

**Comment by mr-mig** [comment]
* [ ] Setup Beanstalk with Docker support 
* [ ] Figure out Ansible + CloudFormation/Terraform integration
* [ ] Create a basic infra on top of Beanstalk via Ansible
* [ ] Security groups and stuff
* [ ] Deploy WebMarks services 
* [ ] Figure out the best way to use a DB (RDS?)
* [ ] Create a deployment pipeline (CodeDeploy?) for docker containers on top of Beanstalk
* [ ] Investigate CI capabilities (https://aws.amazon.com/blogs/apn/leveraging-circleci-and-aws-codedeploy-for-continuous-integration-workflows/)

**Comment by oliversauter** [comment]
How can I like this :D Thanks Alexey for adding! :+1: 
See you tomorrow!

**Comment by lwm** [comment]
@mr-mig 

Apologies if I got to the party too late and am asking / saying stupid things.

[The linked diagram][1] of the infrastructure from this [repo][2] has started to scare me ;)

I wanted to ask:

Have you sync'd up with the hypothesis core devs in order to see how they already setup their infrastructure? I see they have [this guide][3] and are quite easy to contact through [their community section][4]. I am sure they could point us in a good direction for the first iteration of this.

[1]: https://raw.githubusercontent.com/lachatak/deliverypipeline/master/pics/deliverypipeline_flow.jpg
[2]: https://github.com/WorldBrain/infrastructure
[3]: http://h.readthedocs.org/en/latest/INSTALL.html
[4]: https://github.com/hypothesis/h#community

**Comment by lwm** [comment]
Related thread [here][1].
[1]: https://groups.google.com/a/list.hypothes.is/forum/#!searchin/dev/infrastructure/dev/z7YiPN1Vz7g/tN3mod7f_5kJ

**Comment by mr-mig** [comment]
@lwm I haven't synced with them. All the stuff they have is docker-based, so it should work atop any docker-enabled infra.

The diagram is pretty scary if you have never worked with the resulting setup :)
Everything will be automated tho, so for developers it should be a breeze to deploy any change on top of that. 

Feel free to ask me for any kind of details tho. I should be available via gitter, tho the answer delay is pretty huge usually ^__^
